#!/usr/bin/env python3
"""Export velaguard.mthings → CSV + generated C point table for HMI."""

from __future__ import annotations

import csv
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_MTHINGS = REPO / "config/mthings/velaguard.mthings"
OUT_CSV = REPO / "config/mthings/velaguard_sensors.csv"
OUT_C = REPO / "gui/main/ui/model/vg_mthings_points.c"
OUT_H = REPO / "gui/main/ui/model/vg_mthings_points.h"


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load_points(mthings: Path) -> list[dict]:
    root = ET.parse(mthings).getroot()
    dl = root.find("DEVICE_LIST")
    if dl is None:
        raise SystemExit(f"No DEVICE_LIST in {mthings}")

    rows: list[dict] = []
    for dev in dl.findall("DEVICE"):
        addr = int(dev.get("Addr", "0"))
        dname = dev.get("Name", "")
        group = dev.get("cGp", "")
        data_list = dev.find("DATA_LIST")
        if data_list is None:
            continue
        for d in data_list.findall("DATA"):
            if d.get("BLOCK") != "2":
                continue
            prtc = d.get("PrtcTYPE", "1")
            gain = float(d.get("Gain", "1") or "1")
            unit = d.get("Unit", "") or ""
            name = d.get("Name", "")
            reg = int(d.get("Addr", "0"))
            rows.append(
                {
                    "device": dname,
                    "device_id": int(dev.get("ID", "0")),
                    "station": addr,
                    "name": name,
                    "reg": reg,
                    "block": 2,
                    "data_type": "int16" if prtc == "0" else "uint16",
                    "unit": unit,
                    "scale": gain,
                    "group": group,
                }
            )
    rows.sort(key=lambda r: (r["station"], r["reg"]))
    return rows


def write_csv(rows: list[dict], path: Path) -> None:
    fields = [
        "device",
        "device_id",
        "station",
        "name",
        "reg",
        "block",
        "data_type",
        "unit",
        "scale",
        "group",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def write_c(rows: list[dict]) -> None:
    OUT_H.write_text(
        """#ifndef VG_MTHINGS_POINTS_H
#define VG_MTHINGS_POINTS_H

#include <stdint.h>

typedef struct {
    uint8_t addr;
    uint16_t reg;
    uint8_t is_signed;
    float scale;
    const char *name;
    const char *unit;
    const char *dev;
} vg_mthings_point_t;

extern const vg_mthings_point_t vg_mthings_points[];
extern const int vg_mthings_point_count;

#endif
""",
        encoding="utf-8",
    )

    lines = [
        "/* Generated by scripts/gen_mthings_points.py — do not edit. */",
        '#include "vg_mthings_points.h"',
        "",
        "const vg_mthings_point_t vg_mthings_points[] = {",
    ]
    for r in rows:
        signed = 1 if r["data_type"] == "int16" else 0
        lines.append(
            "    { %u, %u, %u, %.6ff, \"%s\", \"%s\", \"%s\" },"
            % (
                r["station"],
                r["reg"],
                signed,
                r["scale"],
                c_escape(r["name"]),
                c_escape(r["unit"]),
                c_escape(r["device"]),
            )
        )
    lines.append("};")
    lines.append("const int vg_mthings_point_count = %d;" % len(rows))
    lines.append("")
    OUT_C.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    src = DEFAULT_MTHINGS
    if not src.is_file():
        print(f"Missing {src}")
        return 1
    rows = load_points(src)
    write_csv(rows, OUT_CSV)
    write_c(rows)
    print(f"Wrote {len(rows)} points -> {OUT_CSV}")
    print(f"Wrote {OUT_C}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
